name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    # Bước 1: Lấy code về
    - uses: actions/checkout@v3
    
    # Bước 2: Build thử Docker Image (Nếu build được nghĩa là code ngon)
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag my-app:latest

    # Bước 3: Kiểm tra xem Image đã được tạo chưa
    - name: Verify Build
      run: docker images